[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
tokio.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic-build.workspace = true

